<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>jadwalSidang</name>
   <tag></tag>
   <elementGuidId>dd6e5b74-f1b4-4cad-9da3-e524a57e9713</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='aside-menu']/ul/li[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7f33ecdf-fb0b-4ebe-93c1-661456008aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://dev-thesis.its.ac.id/sidang/jadwal</value>
      <webElementGuid>b760d902-3348-4224-b463-318ed31c3dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link-its d-flex justify-content-start align-items-center </value>
      <webElementGuid>51a9b1d6-a456-4b56-a440-215c5565cf7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jadwal Sidang</value>
      <webElementGuid>e1ca364c-d949-4727-8273-cfdfd6775aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aside-menu&quot;)/ul[@class=&quot;sidebar-nav ht-100p pd-y-10 scrollbar-its&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link-its d-flex justify-content-start align-items-center&quot;]</value>
      <webElementGuid>79287a7b-75d3-4178-b089-76b9beebfb7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='aside-menu']/ul/li[7]/a</value>
      <webElementGuid>490e67bd-0fd4-43a8-8bd8-08845696b799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rekapitulasi Nilai'])[2]/following::a[1]</value>
      <webElementGuid>d210de63-53e6-4872-810e-8295a1f59149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tugas Akhir Mahasiswa'])[2]/following::a[2]</value>
      <webElementGuid>1e22f114-a552-4e8d-aa4d-07eedca2621a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu Pokok'])[1]/preceding::a[1]</value>
      <webElementGuid>3c681633-647e-4228-bb56-3d46aa0fce4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://dev-thesis.its.ac.id/sidang/jadwal')])[2]</value>
      <webElementGuid>622fb7a8-89c2-40ca-9044-450a0c176ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/ul/li[7]/a</value>
      <webElementGuid>b8643384-f418-46bf-9041-45ce4d25598d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://dev-thesis.its.ac.id/sidang/jadwal' and (text() = 'Jadwal Sidang' or . = 'Jadwal Sidang')]</value>
      <webElementGuid>543adb9e-6218-4f84-9f65-3d22a7137eaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
