<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tugasAkhir</name>
   <tag></tag>
   <elementGuidId>2c2f4517-d98f-4bc0-8f32-09461bae420b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='aside-menu']//a/*[contains(text(),'Tugas Akhir')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2abb9001-e3e6-41f7-80e7-4c5ac7114885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://dev-thesis.its.ac.id/tesis</value>
      <webElementGuid>5f2146be-038e-48d1-b5b9-8424b1e83875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link-its d-flex justify-content-start align-items-center </value>
      <webElementGuid>69c329be-3de2-4cf1-a452-73c45ce2aa3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tugas Akhir</value>
      <webElementGuid>f4a65c60-a018-4d76-a380-72113b762a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aside-menu&quot;)/ul[@class=&quot;sidebar-nav ht-100p pd-y-10 scrollbar-its&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link-its d-flex justify-content-start align-items-center&quot;]</value>
      <webElementGuid>c174f205-3629-4294-b725-6c794cbf4f29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='aside-menu']/ul/li[3]/a</value>
      <webElementGuid>9f1162fb-bb17-48a3-a620-955e936554b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penawaran Topik'])[2]/following::a[1]</value>
      <webElementGuid>0113a655-0b18-4f40-88f1-d3e6c2be2d4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[2]/following::a[2]</value>
      <webElementGuid>4c77747b-2bfb-4055-9f38-35972244deda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Repositori Dokumen Final'])[2]/preceding::a[1]</value>
      <webElementGuid>9d1c2e34-3f34-41a4-a25c-07d8ef109c6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://dev-thesis.its.ac.id/tesis')])[2]</value>
      <webElementGuid>91b9cb5e-efca-4832-b736-a4c86192976c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/ul/li[3]/a</value>
      <webElementGuid>5f622baa-503f-4dee-8618-d4169380e22a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://dev-thesis.its.ac.id/tesis' and (text() = 'Tugas Akhir' or . = 'Tugas Akhir')]</value>
      <webElementGuid>d5b7f4cf-5f0e-4bc2-a954-db2417212bb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
