<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_nonreguler</name>
   <tag></tag>
   <elementGuidId>6371d335-1750-4fe4-812e-81036248d531</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pills-nonreguler-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pills-nonreguler-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>27591af9-9d86-42db-8cf1-888cdd2b8820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link tx-poppins tx-medium</value>
      <webElementGuid>18c6ebd3-0076-4fea-abef-5d8172996721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pills-nonreguler-tab</value>
      <webElementGuid>a14eabba-7ec0-4cad-8706-2160b4d8ea69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>pill</value>
      <webElementGuid>15a9b6e4-3c67-43f1-85d2-c83bc648eeb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#pills-nonreguler</value>
      <webElementGuid>fa90454a-b7d1-4400-99e2-e96a045cb27b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>1696c71a-311a-4017-89bd-c1247d8b4a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pills-nonreguler</value>
      <webElementGuid>07fe99c5-ba3d-4f09-a0be-8e29d5f1feda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>baf6bed6-1c13-41c3-97e0-e3a162f04558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Program Non-Reguler</value>
      <webElementGuid>e5db3a5e-b3e2-4ea3-b899-d1ac4dc093c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pills-nonreguler-tab&quot;)</value>
      <webElementGuid>15df6062-bf75-465f-9a97-3b5ad50a57e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pills-nonreguler-tab']</value>
      <webElementGuid>d26c40f0-be2d-4d15-be72-ddaff6d7d219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pills-tab']/li[2]/a</value>
      <webElementGuid>9277456e-4c0c-4850-be4c-1ee3d04a534a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Program Non-Reguler')]</value>
      <webElementGuid>e4ac1bcd-993f-4a99-9216-787df32b3135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program Reguler'])[1]/following::a[1]</value>
      <webElementGuid>d66649f7-72d1-4cea-b695-15117a519f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semester Genap 2022/2023'])[1]/following::a[2]</value>
      <webElementGuid>8bfd7101-33a1-4c46-95b2-2eee74826212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Bimbingan'])[1]/preceding::a[1]</value>
      <webElementGuid>8b33e6ed-afcc-4926-972a-ab60d9ad6749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tugas Akhir'])[1]/preceding::a[1]</value>
      <webElementGuid>b60f8be8-e0c7-44cf-a49a-804a61435a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Program Non-Reguler']/parent::*</value>
      <webElementGuid>ac6de50c-cf76-419e-9faa-75b5eb0e546a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#pills-nonreguler')]</value>
      <webElementGuid>bbc89054-9895-452f-889d-2a77fdc9a290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li[2]/a</value>
      <webElementGuid>aa198ce4-f0d0-467e-a0ff-62accc475e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pills-nonreguler-tab' and @href = '#pills-nonreguler' and (text() = 'Program Non-Reguler' or . = 'Program Non-Reguler')]</value>
      <webElementGuid>94d3db8f-4466-4857-a4c8-00191f45abeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
