<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labName</name>
   <tag></tag>
   <elementGuidId>9f0bcb5b-0272-402a-89e7-dd80279845fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;table&quot;]/tbody/tr[1]/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>ae729be8-bde8-4a1c-b559-73240f9603bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1679557001985</value>
      <webElementGuid>04ad84a1-2402-48db-8c58-f7879eede90c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
