<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonUploadFileCatatan</name>
   <tag></tag>
   <elementGuidId>7938fab4-d669-4c4b-9a54-bbbd6fd760eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;table-mandiri&quot;]/tbody/tr[2]/td[3]/a[@href='#berkas-add']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
