<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>AdminProdi_S1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>1de28523-23fa-4469-bd38-2609e8b841c6</testSuiteGuid>
   <testCaseLink>
      <guid>a1512e7f-dabb-4672-9ead-5975d85740f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdminProdi/S1/Login_Auth_S1</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4e69e835-117e-4bb8-8182-a5b032164211</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>2</value>
         </iterationEntity>
         <testDataId>Data Files/testData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>4e69e835-117e-4bb8-8182-a5b032164211</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>b4fc7bb1-9dbf-4c8a-9895-07428facb3c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4e69e835-117e-4bb8-8182-a5b032164211</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>c1912035-647e-4ee6-bf0b-4e9b659f2094</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>abe0b087-64a4-419b-a504-d94cb76b10ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdminProdi/S1/Administrasi/DaftarSDMEksternal/pendaftaranSDM</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e5486265-6d01-4fc7-af3a-fcd9cd652e59</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdminProdi/S1/Administrasi/DataLaboratorium/detailLab</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>354c0f2e-57df-4e83-aa2c-45e786ed9353</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b358a48d-b8cc-4e8d-82dc-89eb48be1111</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf3fa05d-4203-4ecb-a833-b0dfb0a0a244</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdminProdi/S1/Administrasi/KonfigurasiDokFinal/konfigDokumenFinal</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>8fec6cef-5375-4552-b517-24b27a9d6246</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdminProdi/S1/Administrasi/KonfigurasiProdi/konfigurasiProdi</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>629c5337-a47c-467b-85ef-1e48a9772dfc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdminProdi/S1/RekapitulasiNilai/rekapitulasiNilai</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5befbc3e-5316-4101-a3a7-53d38affc491</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>086fca6d-79ba-441d-81fe-79a76fd26f74</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb84f105-6dc8-4d39-bee8-654e7bfe50c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdminProdi/S1/Administrasi/PeriodeSidang/periodeSidang</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>9cb46c2b-d8df-4d63-bcd0-289017b8da77</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdminProdi/S1/JadwalSidang/jadwalSidang</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>042fdd4d-5ff8-4025-8b85-26b4caee0713</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdminProdi/S1/PembimbinganDosen/pembimbinganDosen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a677ec7-49ee-4b31-9ace-15b3d598d5f2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d161dc5-5ce3-403e-a233-795a11ef3fee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdminProdi/S1/TugasAkhirMahasiswa/tugasAkhirMahasiswa</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0830e07-365e-4278-ae03-93a8775219dd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>14af5014-750b-4132-bcf4-592eccf567b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AdminProdi/S1/Administrasi/KriteriaPenilaianProdi/kriteriaPenilaian</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5712ec2f-2309-45e6-95cf-48603ffcc5a0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
