<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Mahasiswa</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>36c36e61-0413-48e7-8850-c76be3ad2c19</testSuiteGuid>
   <testCaseLink>
      <guid>57a87ad3-1019-41fe-b25c-d4e3ff9adc83</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/LoginAuth</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>610c48d6-4986-4d16-bdb9-0768dda1e663</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>7</value>
         </iterationEntity>
         <testDataId>Data Files/testData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a32da468-f808-4f5b-b12b-89194c09c978</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>610c48d6-4986-4d16-bdb9-0768dda1e663</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>86bb0dea-ce26-4eed-b923-88eb429df722</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>610c48d6-4986-4d16-bdb9-0768dda1e663</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>54979ee3-044e-4f1d-b10c-fe8504659ff4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>19002c2f-5bdd-449a-a35c-d5ad8baba793</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mahasiswa/pengumuman/pengumuman</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>d2c4e614-0335-4dc7-8209-68c2555472db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mahasiswa/PenawaranTopik/penawaranTopikPage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>0994b227-2c6f-4e97-b52f-33ea169209ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mahasiswa/RepositoriDokumenFinal/repoDokumenFinal</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1a226a80-5e12-4e6e-b772-cbed33273c7f</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>11</value>
         </iterationEntity>
         <testDataId>Data Files/testData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>1a226a80-5e12-4e6e-b772-cbed33273c7f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>e69dad59-9df3-4651-bb59-6c4f0c534c8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1a226a80-5e12-4e6e-b772-cbed33273c7f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>e52e0e3b-b5c7-4d47-b32c-5cfddb0a7cab</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
