<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>terimaUsulanPerubahan</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>c174366f-b9ab-4ea0-90c9-05354ef552cf</testSuiteGuid>
   <testCaseLink>
      <guid>8024a126-8f3c-445f-974c-dcc81ad5bbf7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mahasiswa/TugasAkhir/tugasAkhirUsulkanPerubahanMhs</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>091f0768-095e-45ac-a13c-0ffb1c1146ff</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>6</value>
         </iterationEntity>
         <testDataId>Data Files/testData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>091f0768-095e-45ac-a13c-0ffb1c1146ff</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>aeae370c-e478-4851-b924-62cf6daea78a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>091f0768-095e-45ac-a13c-0ffb1c1146ff</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>04060744-5efc-4c86-a852-8192377ddde6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f242a253-19f6-4139-8cf0-4facec4166b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dosen/bimbinganAktif/terimaUsulanPerubahan</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>62d9478a-d73c-40f9-86fc-284e1942f7fe</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>3-4</value>
         </iterationEntity>
         <testDataId>Data Files/testData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>62d9478a-d73c-40f9-86fc-284e1942f7fe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>e3309e0b-88ba-485e-b712-0e957dc713ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>62d9478a-d73c-40f9-86fc-284e1942f7fe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>1621dff7-2d35-4289-b957-68ad29272eeb</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
