<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>tolakPembimbingan</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>26b073ab-65c5-41f2-8772-ef85b0161cf5</testSuiteGuid>
   <testCaseLink>
      <guid>33c53424-17e6-4d0e-a3ba-2a23cf1d69c0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Mahasiswa/TugasAkhir/tugasAkhirBuatUsulan</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a9ccc637-c22f-4f7d-9ca1-dcf50ca82c61</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>8</value>
         </iterationEntity>
         <testDataId>Data Files/testData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>a9ccc637-c22f-4f7d-9ca1-dcf50ca82c61</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>07a6734c-4752-495e-a620-66871307f008</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a9ccc637-c22f-4f7d-9ca1-dcf50ca82c61</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>a10c3536-30b6-4637-99a6-2f1027daab7a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a7449b13-e78b-4a40-b89e-94f99bcb5009</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dosen/beranda/tolakPembimbingan</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e7278f00-8347-4de2-b53a-8790e2d75da4</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>4-5</value>
         </iterationEntity>
         <testDataId>Data Files/testData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>e7278f00-8347-4de2-b53a-8790e2d75da4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>6062b97e-d187-44d0-985c-27b342c6eb82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e7278f00-8347-4de2-b53a-8790e2d75da4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>d5e98868-e8ca-4053-9680-496f9c77eddb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>99239542-076a-424c-9d56-531d3745b9ee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Mahasiswa/TugasAkhir/tugasAkhirBuatUsulanKelompok</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>393a8f2a-074c-4ad5-bb05-f54b51c0bc89</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>8</value>
         </iterationEntity>
         <testDataId>Data Files/testData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>393a8f2a-074c-4ad5-bb05-f54b51c0bc89</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>160f8ae2-9077-4e0b-bba0-441884607663</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>393a8f2a-074c-4ad5-bb05-f54b51c0bc89</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>00fdf8d9-cdd7-4a04-89b4-c0cd075fd442</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>75364105-ea37-4b9a-98de-21cd83e50a67</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/AdminProdi/S1/AlokasiPembimbingan/alokasiPembimbingan</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>87fd7c99-9b0c-47f6-9ddd-7a10aa559aeb</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>4-5</value>
         </iterationEntity>
         <testDataId>Data Files/testData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>783c8938-0def-4953-a905-a515b0e48ec8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15dce3d4-e14c-4c3f-80e2-418b5e2364fc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
