<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonBerikutnya</name>
   <tag></tag>
   <elementGuidId>ad30c10b-0464-4806-9dfe-0492c1743a55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;pembimbingan-prodi-regular_next&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>20990c4f-0671-4935-a552-6746b92d7a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1681359397743</value>
      <webElementGuid>44785aa8-62c8-4361-a04a-622748d8f83a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
