<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tablePembimbingan</name>
   <tag></tag>
   <elementGuidId>6dae7c64-83d4-4cf5-b426-6285a97f14e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;pembimbingan-prodi-regular&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>00404565-f011-418a-a75e-b5751284d141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1681358854774</value>
      <webElementGuid>4e8eed9c-b16d-4ff1-a426-dd97bfef6370</webElementGuid>
   </webElementProperties>
</WebElementEntity>
