<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan</name>
   <tag></tag>
   <elementGuidId>d63f1d42-72b0-4c50-98e1-a59b532fed66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.mt-2.btn-its-3.tx-poppins.tx-medium.float-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>25910a9e-312d-4d98-85b4-0088eb71589d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>018f6405-9637-4c0d-b760-e6ea0bf1c6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn mt-2 btn-its-3 tx-poppins tx-medium float-right</value>
      <webElementGuid>05843f75-10da-4eda-9209-8996157c011f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Simpan
                        </value>
      <webElementGuid>7a80035f-4117-48a4-97d8-33685c8d3c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formSdmEksternal&quot;)/div[@class=&quot;valign-middle&quot;]/div[@class=&quot;float-right&quot;]/button[@class=&quot;btn mt-2 btn-its-3 tx-poppins tx-medium float-right&quot;]</value>
      <webElementGuid>aace181c-ed9b-406e-88d6-546a4a4a6f8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>7723433e-9df3-4f4a-9f43-ebfac28c72dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSdmEksternal']/div[4]/div/button</value>
      <webElementGuid>00d1bbbe-0e83-4ff5-8966-e895b12ae325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NPWP'])[1]/following::button[1]</value>
      <webElementGuid>f4e9c682-0d28-4fd4-9ada-d0cb3103b670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Afiliasi'])[1]/following::button[1]</value>
      <webElementGuid>71769c35-95af-4147-bc4d-08e71f3c10f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2021-2023 Institut Teknologi Sepuluh Nopember'])[1]/preceding::button[1]</value>
      <webElementGuid>a6de7be5-e34d-4ad8-b6be-7ada0066cd73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2021-2023 Institut Teknologi Sepuluh Nopember'])[2]/preceding::button[1]</value>
      <webElementGuid>198963b2-b2b3-4517-8867-d90c3e53e5a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Simpan']/parent::*</value>
      <webElementGuid>c9284619-5596-4ab1-85d8-6acc70923662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button</value>
      <webElementGuid>b97de7d4-f5e0-45ed-b00f-a668ce21582f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                            Simpan
                        ' or . = '
                            Simpan
                        ')]</value>
      <webElementGuid>ffb6fadb-6ec8-4140-b546-1ebc68ab9e8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
