<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputNIK</name>
   <tag></tag>
   <elementGuidId>268920c9-a303-4d59-8407-862ad84c8af7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;field_nik&quot;]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nomor_paspor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75c95b32-1ff3-4270-9db8-9e39558c894a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5d475127-4405-42c0-97ba-bbf7fe099053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>be0e620e-4f2e-4b29-8177-092994bf874a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nomor_paspor</value>
      <webElementGuid>2807ef49-5507-444e-97ac-194c1e0b2f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nomor_paspor</value>
      <webElementGuid>ab281a09-b5cb-46c7-bbcc-17d437151445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>73900e84-342c-4fbc-a70f-1aa0e5913b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>067e9392-b0f6-499e-8ad6-1d72b4003af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>(?=.{6,16}$)([a-zA-Z0-9]{1,3}[-]{0,1}[a-zA-Z0-9]*)</value>
      <webElementGuid>06134f7b-b6b3-4bd2-9cb9-ac244bb700c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Format: 6-16 karakter huruf/angka. Karakter pertama harus huruf/angka.
                                Karakter '-' boleh muncul hanya 1x.</value>
      <webElementGuid>15976d77-f8c2-42c6-aec1-ca27a9a5495e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>1d449c52-f6ed-4830-94ae-305fae0377a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nomor_paspor&quot;)</value>
      <webElementGuid>96d36053-ef47-43b0-9ebf-e78569c76866</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nomor_paspor']</value>
      <webElementGuid>01edb49f-4abb-472a-a86c-775e169271d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field_nmr_paspor']/input</value>
      <webElementGuid>585224a1-e052-49c2-9c4e-3fd9e8c69048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>974f3789-b22b-44aa-98a9-63f6349ff435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nomor_paspor' and @name = 'nomor_paspor' and @title = concat(&quot;Format: 6-16 karakter huruf/angka. Karakter pertama harus huruf/angka.
                                Karakter &quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot; boleh muncul hanya 1x.&quot;)]</value>
      <webElementGuid>42373a24-95d8-4753-9124-ff5eecc9cc0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
