<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputGelarDepan</name>
   <tag></tag>
   <elementGuidId>315b76a6-c5e7-4032-a542-a371be1b1932</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gelar_depan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gelar_depan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dadd6805-56a6-4683-a62a-1dcfcab41fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1c2822e9-50fc-43fc-90f1-9937af70fc19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>53c2fa0d-ae0f-4c11-bce1-0d61b201da7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gelar_depan</value>
      <webElementGuid>18a76b56-708e-4871-ab7d-cdf7a1d718a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gelar_depan</value>
      <webElementGuid>282e46c8-f759-4ec2-af72-659840e4626b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gelar_depan&quot;)</value>
      <webElementGuid>d335a975-29bd-48a9-8991-ec876c7f2699</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gelar_depan']</value>
      <webElementGuid>63a9eaa4-ad91-42ec-bc70-ba59d28f9e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSdmEksternal']/div/div[2]/div/input</value>
      <webElementGuid>df9a73c1-39a7-4176-b329-37fbf8072667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>23dc73fd-8ccb-4020-8c1d-e65718694802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'gelar_depan' and @name = 'gelar_depan']</value>
      <webElementGuid>e78663d4-9b21-42e2-bb4a-a832c7be23bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
