<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>abstrakEn</name>
   <tag></tag>
   <elementGuidId>2920a625-b38f-4419-8db4-f381fc3820a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='abstrak_en']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#abstrak_en</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3361c15e-ea8a-42df-81e9-9f231eb7f858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d3b68658-6278-4a92-a585-fcf04b5a83d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Aa</value>
      <webElementGuid>fa914c6a-f8e6-47cb-9fb4-942e0ca8134f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>abstrak_en</value>
      <webElementGuid>ad739939-5bbe-4f0f-9821-48646e36d220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>abstrak_en</value>
      <webElementGuid>94ea9df4-827f-4162-9c19-130c3d3c2c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;abstrak_en&quot;)</value>
      <webElementGuid>98f997ce-f1f5-4a9b-8e53-de0e9126bc4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='abstrak_en']</value>
      <webElementGuid>be280629-13cb-4f26-a22e-4a65c418bfda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formTambahTesisMhs']/div[6]/textarea</value>
      <webElementGuid>77747baa-47a6-44a7-b4ee-8f501da27625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/textarea</value>
      <webElementGuid>aee0e024-a64e-4f46-8558-5dbf2523510f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Aa' and @id = 'abstrak_en' and @name = 'abstrak_en']</value>
      <webElementGuid>0c3cca3f-f776-4b17-8bee-b164e9d52ee4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
