<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>judul</name>
   <tag></tag>
   <elementGuidId>9d707593-b6b2-44ed-82b9-29cd77fcefb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='judul-id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#judul-id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>cfcbf294-0304-4ddc-963b-2c35536db0a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d18189d4-ffb4-40a7-9305-1ef5a1ee7bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Aa</value>
      <webElementGuid>912abe9e-7684-4240-ad51-b50e48ce4ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>judul-id</value>
      <webElementGuid>19b52d89-5858-4cb5-b6af-9eaff9f0dc7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>judul</value>
      <webElementGuid>97528a68-757b-4f32-af7d-588d329db26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;judul-id&quot;)</value>
      <webElementGuid>3afbf98b-640c-48f5-816d-9abe24a66ec6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='judul-id']</value>
      <webElementGuid>b6bdb67d-222f-4ca7-a8b4-a76f9d62a43c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formTambahTesisMhs']/div[3]/textarea</value>
      <webElementGuid>76dcd40b-fce8-4c70-9bfa-f253f4642026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>8c58e04a-c8a9-4fa0-9d89-0b8031a25d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Aa' and @id = 'judul-id' and @name = 'judul']</value>
      <webElementGuid>7f2c2bb5-fad2-41c7-aa0d-d8ed60910fd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
