<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kataKunciEng</name>
   <tag></tag>
   <elementGuidId>f330350e-6637-467b-b83a-fadd1758b790</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;formTambahTesisMhs&quot;]/div[8]/div[1]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fffe4532-a98d-482a-81f7-099ee6fe720e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bootstrap-tagsinput</value>
      <webElementGuid>6c0da871-c022-487a-9113-0e98c555fca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formTambahTesisMhs&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;bootstrap-tagsinput&quot;]</value>
      <webElementGuid>17cde2cb-feb4-48a6-9b34-c354563c5b3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formTambahTesisMhs']/div[8]/div</value>
      <webElementGuid>5d18cd57-aeb2-4416-b212-2bb320b0ac1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::div[1]</value>
      <webElementGuid>6a229ba2-76ae-4d7c-8787-d79f962e042c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mohon masukkan Kata Kunci Bahasa Inggris'])[1]/preceding::div[1]</value>
      <webElementGuid>048f9d55-a771-43ae-9920-d6dab9dc8f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak Berkelompok'])[1]/preceding::div[3]</value>
      <webElementGuid>a6e9be7e-bb14-4153-8fc0-ba33eb09ada1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div</value>
      <webElementGuid>34c68982-1f3d-40f8-8f1e-7b398fec9410</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
