<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kataKunci</name>
   <tag></tag>
   <elementGuidId>45b920d6-8eaa-4cb1-bcae-29f23996de0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;formTambahTesisMhs&quot;]/div[7]/div[1]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>559f0bb7-0f90-411a-91ad-8009dae66457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bootstrap-tagsinput</value>
      <webElementGuid>9550076c-417e-4445-b412-6c39b4b3f3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formTambahTesisMhs&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;bootstrap-tagsinput&quot;]</value>
      <webElementGuid>cf98d5c8-0f2c-42e1-a890-d224fc3043ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formTambahTesisMhs']/div[8]/div</value>
      <webElementGuid>0231e63a-3262-41d5-91f0-889230cfa768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::div[1]</value>
      <webElementGuid>86c1f69d-e496-4e1e-867a-3f1ff5b58f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mohon masukkan Kata Kunci Bahasa Inggris'])[1]/preceding::div[1]</value>
      <webElementGuid>a4fc8259-0681-4693-8338-42d98c2b9447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak Berkelompok'])[1]/preceding::div[3]</value>
      <webElementGuid>d75c26bd-a8a4-456a-bdea-89dae6741a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div</value>
      <webElementGuid>15a4dfc6-d8e2-4e92-ae5e-91f261a95fcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
