<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mahasiswa</name>
   <tag></tag>
   <elementGuidId>12069155-d6cb-433c-b304-b6dbe4df5a23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;formTambahTesisMhs&quot;]/div[2]/span/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>edd3b455-b4c3-4ca0-a1c8-d0b1c5fd8a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1684305632850</value>
      <webElementGuid>f177a0cf-3d97-49a8-9795-e5637931aa8f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
