<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_tesis</name>
   <tag></tag>
   <elementGuidId>61f9d285-e9a7-4d9e-b8b2-72a0019d062d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;tesis-tab&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>d7ba73ce-f186-4f57-88a9-0d431746b909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1685804609139</value>
      <webElementGuid>1ad686d1-2127-47d9-915f-c875f818235b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
