<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>adaSidangProposal</name>
   <tag></tag>
   <elementGuidId>0ab9957e-9b85-4549-b4bc-a7a8db8c8e3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[2]/div/div/form/div/div[2]/div[1]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>e3c2a5ce-8fb6-401a-b388-7ac24d9a55a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1679886187375</value>
      <webElementGuid>c9e7362d-4fcd-4cd5-b95b-26732eb4b1fa</webElementGuid>
   </webElementProperties>
</WebElementEntity>
