<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>resultPIC</name>
   <tag></tag>
   <elementGuidId>61c02b12-d7fe-47ca-af6e-6506ad954058</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;select2-id_sdm_0-results&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>da7c725c-6e80-4d9a-8ff2-368d7e0177a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1679888777992</value>
      <webElementGuid>901a820e-0812-49fe-a399-44ffc728225b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
