<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tidakAdaSidangAkhir</name>
   <tag></tag>
   <elementGuidId>3aaa380d-6b75-446b-97b8-9c264f066944</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[2]/div/div/form/div/div[10]/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>8f569083-0479-4231-941f-a70b581788fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1679886732904</value>
      <webElementGuid>e184f7fc-b62a-41cb-aa3d-2e212e65ee6d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
