<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tidakAdaSidangProposal</name>
   <tag></tag>
   <elementGuidId>a5ddaccd-e193-4df3-b3af-9bb059c309c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[2]/div/div/form/div/div[2]/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>94f2d938-7875-484d-906a-946a0791154b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1679886201234</value>
      <webElementGuid>bdf46de6-12a2-4614-a73e-101d68c2bd7a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
