<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kuotaPendaftaran</name>
   <tag></tag>
   <elementGuidId>0c94196a-6905-40c8-a3ea-62d788a3902d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;kuota&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>794632ed-01d4-4fba-87f6-f264d1aa2d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1679970238150</value>
      <webElementGuid>8d340fe0-0585-4d87-b4ed-f550adf00ad8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
