<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>namaSidangInggris</name>
   <tag></tag>
   <elementGuidId>a1680fd1-b5cd-4177-b232-57b36aca8464</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;nama_en&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>601b8f27-0920-4214-aaae-6a889d2849df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1679970210774</value>
      <webElementGuid>3ade11d4-0c31-4a16-ab8d-0cf3c59a5f95</webElementGuid>
   </webElementProperties>
</WebElementEntity>
