<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchAdminSidang</name>
   <tag></tag>
   <elementGuidId>35e6faef-79c9-4fff-ac9d-621aec045f32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/span/span/span[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>7f1c6406-0fed-4adb-9393-bfb273822090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1679970327896</value>
      <webElementGuid>1cc8e22a-f14d-4eaa-b8a8-7bde9deeb8c4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
