<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tanggalMulaiSidang</name>
   <tag></tag>
   <elementGuidId>ebdf2bdb-03f8-4833-834d-0d71946658d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;tgl_mulai_sidang&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>0f55def6-bc4a-4b4b-8204-2b330e266eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1679970432298</value>
      <webElementGuid>9117de7c-6a1b-4f95-9642-752aaf06dc7b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
