<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tanpaKuotaPendaftaran</name>
   <tag></tag>
   <elementGuidId>9eb2fca0-a804-4251-9096-b3aaf9a57994</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[2]/div[1]/div/div/form/div[4]/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>53cab194-5945-4939-a078-81e4e914c726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1679970254295</value>
      <webElementGuid>2c908636-70f7-496b-9899-8fbde16f3983</webElementGuid>
   </webElementProperties>
</WebElementEntity>
