<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonNonActive</name>
   <tag></tag>
   <elementGuidId>8c50a023-16a6-43a7-aa2d-18f63fd65ad2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table']/tbody/tr/td[6]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-item-its.update-status.tx-poppins.tx-medium</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bee1eff2-cc53-493a-8006-b15a2abdb369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0); </value>
      <webElementGuid>8798bb8f-aa33-4783-854c-496c9f8315f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>F58EBF37-A269-4891-B192-53BD2781E338</value>
      <webElementGuid>293a4f9a-a357-4ef1-b0d1-1ee08e816185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-status</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6a205f49-e677-4d22-817a-f554faec9848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item-its update-status tx-poppins tx-medium</value>
      <webElementGuid>e68609b0-ed81-4658-82b4-dd6fd4d78cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nonaktifkan</value>
      <webElementGuid>fe5262f5-7916-4ca3-8035-2950447dc823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;table-its tx-poppins&quot;]/div[@class=&quot;dropdown show&quot;]/div[@class=&quot;dropdown-menu dropdown-menu-right rounded-its-10 blur-transparent show&quot;]/a[@class=&quot;dropdown-item-its update-status tx-poppins tx-medium&quot;]</value>
      <webElementGuid>864684cd-7b87-4fcc-a99f-90aa872f1e9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table']/tbody/tr/td[6]/div/div/a</value>
      <webElementGuid>e5317bbc-8591-4b10-8a6e-960fff8c610d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Nonaktifkan')]</value>
      <webElementGuid>98d20157-0270-4720-8fa0-4d13b9f51791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktif'])[3]/following::a[2]</value>
      <webElementGuid>4255b6de-850b-4d2e-8cd6-372743384817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Topik penelitian baru'])[1]/following::a[2]</value>
      <webElementGuid>b4944408-433a-4b04-8314-9facc8d63839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[1]/preceding::a[1]</value>
      <webElementGuid>b43e4dbd-8e62-40eb-8bb6-0c235d8f73a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Metode Penelitian (sesuai RQ &amp; detail)'])[1]/preceding::a[2]</value>
      <webElementGuid>dec01249-c4d0-466e-90c9-e8e0534de895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nonaktifkan']/parent::*</value>
      <webElementGuid>8e01ce80-89c1-46aa-81f2-6a4b00205924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0); ')]</value>
      <webElementGuid>c96c303a-d999-44e1-afb1-0f9626fd2731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/div/a</value>
      <webElementGuid>cb5d0827-1bc3-4abe-bb18-3b5c0fa21997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0); ' and (text() = 'Nonaktifkan' or . = 'Nonaktifkan')]</value>
      <webElementGuid>bf8b9436-291e-4ebb-aec4-e3c0c7c48447</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
