<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_moreButton</name>
   <tag></tag>
   <elementGuidId>dd701c5f-cb5e-4b2c-88e0-e7c868b589ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table']/tbody/tr/td[6]/div/a/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.avatar-initial.rounded-circle.btn-its-custom-1.tx-color-01</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9751f73e-e416-40ff-8341-331fa6a5c01e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>avatar-initial rounded-circle btn-its-custom-1 tx-color-01</value>
      <webElementGuid>272aa7aa-6bfe-4e18-b8f5-8d0dbd4986c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>6868d8bc-58a0-45d9-897c-1e9d7872d194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>6d24ad67-b91f-40d4-a240-661bfe0731fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Menu</value>
      <webElementGuid>5b723400-6523-4fa4-82d9-886b6aa93f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;table-its tx-poppins&quot;]/div[@class=&quot;dropdown&quot;]/a[@class=&quot;btn btn-icon pd-0&quot;]/div[@class=&quot;avatar&quot;]/span[@class=&quot;avatar-initial rounded-circle btn-its-custom-1 tx-color-01&quot;]</value>
      <webElementGuid>53bea9ca-a5b1-4386-8c73-ecfe0f2eaea2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table']/tbody/tr/td[6]/div/a/div/span</value>
      <webElementGuid>be831ac9-68ad-4c8e-9379-7ca0926b1521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktif'])[3]/following::span[1]</value>
      <webElementGuid>d8e923aa-935b-4092-9097-6235789c81d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Topik penelitian baru'])[1]/following::span[2]</value>
      <webElementGuid>68b53117-797b-4a36-b0d7-68b830d8b8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nonaktifkan'])[1]/preceding::span[1]</value>
      <webElementGuid>60aeae45-55c4-4377-8b09-3108f6164f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[1]/preceding::span[2]</value>
      <webElementGuid>2c3ad6b4-37a1-4d70-a784-7990f0686aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/a/div/span</value>
      <webElementGuid>77d8d13f-d983-4c52-9dda-fc9fd014fc99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Menu']</value>
      <webElementGuid>73922585-82e9-4bd9-844d-8e1142448e8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
