<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonDelete</name>
   <tag></tag>
   <elementGuidId>58d616d3-cd26-4d02-9394-acf9716dc781</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-delete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-delete > span.avatar-initial.rounded-circle.bg-black-1.tx-color-01</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3959ea03-d836-4cbe-a8df-6cf9601169ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>avatar-initial rounded-circle bg-black-1 tx-color-01</value>
      <webElementGuid>a8b17ce1-26fb-4995-aa4d-b5bd2e8b5606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[1]/div[@class=&quot;content ht-100v pd-0&quot;]/div[@class=&quot;content-body mn-ht-100v d-flex flex-column&quot;]/div[@class=&quot;container pd-x-0 mg-t-50&quot;]/div[@class=&quot;row row-xs&quot;]/div[@class=&quot;col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mg-b-10 mg-md-b-10&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body card-list table-responsive&quot;]/div[@class=&quot;card-list-item&quot;]/div[@class=&quot;form-row&quot;]/div[@class=&quot;col-1&quot;]/div[@id=&quot;row&quot;]/button[@id=&quot;btn-delete&quot;]/span[@class=&quot;avatar-initial rounded-circle bg-black-1 tx-color-01&quot;]</value>
      <webElementGuid>0011c722-bb23-45b1-af49-82de12352096</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btn-delete']/span</value>
      <webElementGuid>05175ec0-2c75-4e20-9068-e14fc6e37052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfigurasi Dokumen Final'])[1]/following::span[2]</value>
      <webElementGuid>22545762-7a83-4c6b-a2cc-a825bfe44a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengumuman'])[2]/following::span[2]</value>
      <webElementGuid>b21aca7f-4c55-4e0c-9e7c-948fb48b2278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Kelengkapan Dokumen'])[1]/preceding::span[11]</value>
      <webElementGuid>cdc00918-cae1-4b10-8c35-18a0981e05e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Dokumen'])[7]/preceding::span[11]</value>
      <webElementGuid>35db6434-3ad8-4952-9e94-815c8073316d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>53a3379b-4943-4e51-b376-e3f2d26271d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
