<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputKeteranganEdit</name>
   <tag></tag>
   <elementGuidId>465ff301-3e1e-4cbd-8f95-ad87eb1dc93b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='keterangan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#keterangan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2fc8e73f-f5ca-4c2e-9aca-7b869dfab3ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c74fcae3-e89f-4e39-8993-373a64aabf9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keterangan</value>
      <webElementGuid>53be9328-6c6b-4df6-943a-e2423f17231e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>prasyarat[0][keterangan]</value>
      <webElementGuid>ac7c298d-b887-49bf-83fc-4e2e4f1410de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Keterangan</value>
      <webElementGuid>6c0bfb18-dd81-430f-81f3-f863ac82df8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-edit&quot;)/div[@class=&quot;modal-body&quot;]/div[@class=&quot;form-group form-floating&quot;]/input[@id=&quot;keterangan&quot;]</value>
      <webElementGuid>0bfadbb3-cb71-4a6b-b258-380a90179e84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='keterangan']</value>
      <webElementGuid>0125d9ec-96ba-4b20-85b9-99897999a668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-edit']/div/div[2]/input</value>
      <webElementGuid>041e32a6-220a-4e4b-8728-b3d4d9deb135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>dd941ab6-c8c0-4e61-af8c-332319d22189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'keterangan' and @name = 'prasyarat[0][keterangan]' and @placeholder = 'Keterangan']</value>
      <webElementGuid>4b01b555-d13b-441e-8078-92b0108ee0bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
