<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputFormRow</name>
   <tag></tag>
   <elementGuidId>76ea5a0e-ab64-44e9-b22f-802a0116871a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;inputFormRow&quot;]/div[1]/div[1]/span/span[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>ca2938fe-4a50-456f-a7cd-8c44355b3438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1684209067566</value>
      <webElementGuid>bd272d5e-4a9f-4c22-878a-1ebea363ae34</webElementGuid>
   </webElementProperties>
</WebElementEntity>
