<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectJenisSidang</name>
   <tag></tag>
   <elementGuidId>ffc544ab-805f-4e96-9631-9dcf9b79e33b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[2]/div[2]/div/div/div[1]/div[2]/div/span/span[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>a298f530-35f7-49ff-bb10-bcba3e36b9ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1681363656594</value>
      <webElementGuid>67799614-2840-4c59-9c03-7212877bfe80</webElementGuid>
   </webElementProperties>
</WebElementEntity>
