<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectSemester</name>
   <tag></tag>
   <elementGuidId>06b256ef-dfd9-435c-9966-402ae44f5c35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.select2-search__field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[2]/div[2]/div/div/div[1]/div[1]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>861d82bd-ac30-4866-a684-a859ddd4eac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1681364610985</value>
      <webElementGuid>d822c899-c156-477d-afbb-0ee364fc1c45</webElementGuid>
   </webElementProperties>
</WebElementEntity>
