<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>persentase</name>
   <tag></tag>
   <elementGuidId>8e619597-92d3-497b-b0be-e5c4c1922f09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;persentase&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>a47fe6de-349c-428c-9aaf-3c4ebf21482a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1680663142955</value>
      <webElementGuid>299b41ed-9a02-4e2b-913d-6af5d77c9f35</webElementGuid>
   </webElementProperties>
</WebElementEntity>
