<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_statusTopik</name>
   <tag></tag>
   <elementGuidId>039585d1-84da-4dfb-9221-80f5ecd9e347</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='topik']/tbody/tr/td[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5586e45d-2b95-4608-9205-d4e0b536f529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-its</value>
      <webElementGuid>de1ffc64-7abb-424a-8737-11fd4cbcdda6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Belum diambil</value>
      <webElementGuid>3a6adb7b-9145-40b3-ae1b-b8b004adacaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topik&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;table-its&quot;]</value>
      <webElementGuid>11d3fb36-1f36-4408-82e5-8e8d85938834</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='topik']/tbody/tr/td[6]</value>
      <webElementGuid>549b7791-b169-4bc1-9f8c-ab6d0f295d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hudan Studiawan, S.Kom., M.Kom., Ph.D.'])[1]/following::td[1]</value>
      <webElementGuid>df198c43-d0dd-45b6-9cbe-6cc5efe6ee0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rizky Januar Akbar, S.Kom., M.Eng.'])[1]/following::td[1]</value>
      <webElementGuid>2c08155e-76cd-4fdf-9f8a-985f7eef6334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rizky Januar Akbar, S.Kom., M.Eng.'])[2]/preceding::td[5]</value>
      <webElementGuid>ce88824f-6f0d-48eb-9de6-bc9fbfa09bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]</value>
      <webElementGuid>25bd616b-6b77-4383-bc36-84b00b2f4297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Belum diambil' or . = 'Belum diambil')]</value>
      <webElementGuid>76f6f5d2-e7f0-448d-add6-6d4bd9b9a2ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
