<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>disertasi_ajuansidang</name>
   <tag></tag>
   <elementGuidId>9a0b8bf4-e585-4ca0-9463-46e6495a86b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;pills-sidang-disertasi&quot;]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>3fe18ec7-eeb2-4c46-aa02-459257f30349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1685807019350</value>
      <webElementGuid>5e870a71-37ab-49c7-b2f5-560009ab6a82</webElementGuid>
   </webElementProperties>
</WebElementEntity>
