<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pemimpinSidang_sidang_tesis</name>
   <tag></tag>
   <elementGuidId>876d33f6-2dd8-411b-bc9e-83ffa5cabdd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;pills-sidang-admin-tesis&quot;]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>0955a6bf-1e18-4f86-a5bb-bd03550e813a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1685807381732</value>
      <webElementGuid>0563d1d8-390b-4257-8797-368991bb7260</webElementGuid>
   </webElementProperties>
</WebElementEntity>
