<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pemimpinSidang_sidang_disertasi</name>
   <tag></tag>
   <elementGuidId>729980d9-5e8e-463e-ba9e-0c77c1b2346f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;pills-sidang-admin-disertasi&quot;]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>d680de1f-0125-48e2-90d8-5530f109e4ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1685807416969</value>
      <webElementGuid>e21a232e-60be-401c-bbc9-4e2d197d33b8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
