<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pengujiDisertasi_sidang</name>
   <tag></tag>
   <elementGuidId>971e5d5d-8912-49f8-a78a-7fb871abf15a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;pills-sidang-dospeng-disertasi&quot;]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>de788297-d012-4726-b83a-81d5b1b4a864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1685807224503</value>
      <webElementGuid>30fa9759-4ca0-4f62-9606-35f2f63e1055</webElementGuid>
   </webElementProperties>
</WebElementEntity>
