<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pengujiTa_revisi</name>
   <tag></tag>
   <elementGuidId>b51a4e7a-220f-4575-9db9-0ee03812a83d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;pills-sidang-dospeng-ta&quot;]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>0434f319-ae1b-4a1d-a6e4-75a16a0a420a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1685807165091</value>
      <webElementGuid>f8e4e4cc-1ca5-4bbc-b039-417a05406b9b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
