<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ta_jadwalsidang</name>
   <tag></tag>
   <elementGuidId>7d317c05-ca23-43a1-8c7d-f299593c0bd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;pills-sidang-ta&quot;]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>879baf89-acf7-4338-848b-4985181d8132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1685806940848</value>
      <webElementGuid>96fd30f1-59c4-4797-88c7-168b50024e22</webElementGuid>
   </webElementProperties>
</WebElementEntity>
