<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_tesis</name>
   <tag></tag>
   <elementGuidId>9b919d1e-1344-4f9f-93b7-503b6fb682be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pills-sidang-tesis-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pills-sidang-tesis-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f8315ec5-92ae-4d8e-80d4-e3ad2623e510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link tx-poppins tx-medium</value>
      <webElementGuid>be52fcfd-f847-48a4-bab3-0005e19a64fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pills-sidang-tesis-tab</value>
      <webElementGuid>f8d2f295-b1b6-49e9-bfa6-5660c9b1cefc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>pill</value>
      <webElementGuid>fc02ab9d-1016-4612-a78e-b225017b4eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#pills-sidang-tesis</value>
      <webElementGuid>94528450-90bb-4a7e-b989-06bfc9be7e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>fdd29344-afd6-4ace-b595-b1a5ef328a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pills-sidang-tesis</value>
      <webElementGuid>987c540f-9172-48c1-bd36-ec24c658dcd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>718bbd69-654e-43f8-afc5-9bdabc8bd841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tesis</value>
      <webElementGuid>48a79e24-a00f-4135-9c39-7e4a578b0f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pills-sidang-tesis-tab&quot;)</value>
      <webElementGuid>edb579eb-e3e7-427c-9e19-929fc79c0876</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pills-sidang-tesis-tab']</value>
      <webElementGuid>68731423-4b2f-4aed-85ee-19b3b6491e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pills-tab-sidang']/li[2]/a</value>
      <webElementGuid>c9c63024-0e7d-4a7b-a957-7230ed972ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tesis')]</value>
      <webElementGuid>17386abf-5015-42ff-a230-0c97569ab430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tugas Akhir'])[1]/following::a[1]</value>
      <webElementGuid>b6c3a496-f10f-42a8-b6bc-f4f035a920e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sebagai Dosen Pembimbing'])[1]/following::a[2]</value>
      <webElementGuid>bf6e1888-b691-49cb-8f39-4f33d87a17a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disertasi'])[1]/preceding::a[1]</value>
      <webElementGuid>d7cb6462-7be0-4d20-b772-8dd0c9b2c3a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sebagai Dosen Penguji'])[1]/preceding::a[8]</value>
      <webElementGuid>88f23d25-663b-4989-993e-6bf85ecf2fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tesis']/parent::*</value>
      <webElementGuid>2355732d-a1e5-441e-b21e-bdc51fc8b9f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#pills-sidang-tesis')]</value>
      <webElementGuid>ca37691f-1ff5-4c94-9d0e-a5df2a3c42ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li[2]/a</value>
      <webElementGuid>2e000421-3d4b-4e5f-9b99-7b79ea98f83e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pills-sidang-tesis-tab' and @href = '#pills-sidang-tesis' and (text() = 'Tesis' or . = 'Tesis')]</value>
      <webElementGuid>3f503788-ea29-4d59-9b4d-f2e99610e030</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
