<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tesis_ajuansidang</name>
   <tag></tag>
   <elementGuidId>311afd46-f7b5-4e41-9fea-789d4379d274</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;pills-sidang-tesis&quot;]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>dcd69d2e-2d69-4f8e-af3a-b3100b49f626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1685806961472</value>
      <webElementGuid>43908cda-cec6-4f67-af59-ad67fc8c4127</webElementGuid>
   </webElementProperties>
</WebElementEntity>
