<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Caps lock is on_logo</name>
   <tag></tag>
   <elementGuidId>d6c7c629-c637-4d49-9411-03573134dcdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Logo ITS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1f91f1a6-2488-4c4d-aba5-e5f4f2a3fe6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://dev-my.its.ac.id/assets/media/img/@2x/logo.png 2x, https://dev-my.its.ac.id/assets/media/img/logo.png 1x</value>
      <webElementGuid>6e7d8361-29d7-4dc7-850a-649df0735b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev-my.its.ac.id/assets/media/img/logo.png</value>
      <webElementGuid>aea25f5c-2dcb-45cb-b5be-99ef74d593a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo ITS</value>
      <webElementGuid>c4f47420-5f60-4e82-a441-f6753cdfdbae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>a5024415-2f57-4488-a8da-63928df17045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;box&quot;]/img[@class=&quot;logo&quot;]</value>
      <webElementGuid>0e901a10-9bb5-4ba3-90db-ef77e5e96088</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo ITS']</value>
      <webElementGuid>699bf533-f593-4a6d-bac2-7e97e562fe15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>3b882fe3-5536-4825-9bce-b26d10f7f23b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dev-my.its.ac.id/assets/media/img/logo.png' and @alt = 'Logo ITS']</value>
      <webElementGuid>b54bd4c8-bd82-4987-ab91-7747d831f492</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
