<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputDeskripsiEdit</name>
   <tag></tag>
   <elementGuidId>8411d835-49d1-43f0-98b3-81ad1f79a339</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;editKriteria-05330495-AB12-40D3-95FB-B760E0B217D8&quot;]//*[@id=&quot;deskripsi&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
