<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>jenisSidang</name>
   <tag></tag>
   <elementGuidId>fc7e3525-125b-4320-b343-3cea68aa538e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[2]/div[1]/div/div/div[2]/div[1]/div/span/span[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>e8bd0140-7912-4de0-8435-680a28410e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1680662914997</value>
      <webElementGuid>b4d7a04a-c65a-4e07-8c3f-cdf7b30c0132</webElementGuid>
   </webElementProperties>
</WebElementEntity>
