<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>abstrakBaruEn</name>
   <tag></tag>
   <elementGuidId>92e4c0be-0ee5-4e7a-a343-90ce9239c01d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#abstrakBaruEn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='abstrakBaruEn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1b844830-f8df-4bdd-8c31-4686d0641c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-field</value>
      <webElementGuid>a1736068-623d-4143-8a2c-82dc1e8e9972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>abstrakBaruEn</value>
      <webElementGuid>26224d04-155c-4ec7-8511-ee2907f303f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>abstrak_baru_en</value>
      <webElementGuid>3f862ab0-b61a-478b-a32d-5bb12cab3bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;abstrakBaruEn&quot;)</value>
      <webElementGuid>741d9f28-d171-4b28-ab12-c5d20ce07095</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='abstrakBaruEn']</value>
      <webElementGuid>596434de-d1cc-4244-b617-3ef99d6c266e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/textarea</value>
      <webElementGuid>a5786b1f-8a14-4e0d-bf89-104c5241619a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'abstrakBaruEn' and @name = 'abstrak_baru_en']</value>
      <webElementGuid>0acb4bb7-9ac4-4da6-b5cc-4eb6489caea2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
