<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>abstrakBaru</name>
   <tag></tag>
   <elementGuidId>d6b67ba6-f53a-4c9f-91af-8414da1859bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#abstrakBaru</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='abstrakBaru']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4f5384ee-6680-43ab-9e31-85373630304d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-field</value>
      <webElementGuid>946da0f7-5b63-48dd-bc25-cfe45019e090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>abstrakBaru</value>
      <webElementGuid>a49feeab-65ba-4f6e-b0ae-71a3d6160500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>abstrak_baru</value>
      <webElementGuid>7f4bc0f8-a4ac-40fb-9e89-3ed16e9dd8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;abstrakBaru&quot;)</value>
      <webElementGuid>5a4b1038-1d66-4055-b555-43899e4cda4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='abstrakBaru']</value>
      <webElementGuid>818d11c1-5018-407d-a4c4-9dd60e0a3d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/textarea</value>
      <webElementGuid>968f28e0-6d7f-433a-9462-87b6539f338c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'abstrakBaru' and @name = 'abstrak_baru']</value>
      <webElementGuid>f70ea912-e191-43f4-a916-3ccdf933278d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
