<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>judulBaruEn</name>
   <tag></tag>
   <elementGuidId>6d223e69-2886-40b1-8f67-dc05e819594e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#judulBaruEn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='judulBaruEn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c77748c9-a1ce-4ced-b839-694eaa731df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-field</value>
      <webElementGuid>e589d372-a702-45d6-8791-dad2cb8efeb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>judulBaruEn</value>
      <webElementGuid>5fa38b84-a053-48a4-97e8-935f27bfa615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>judul_baru_en</value>
      <webElementGuid>0a8a01ed-e8f1-4936-a15a-39a38e4c4517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>39124d24-9ad8-4b7a-b0a0-365693743f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;judulBaruEn&quot;)</value>
      <webElementGuid>601059e9-e87a-48f8-9f8f-94e802f83562</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='judulBaruEn']</value>
      <webElementGuid>6e735647-6dae-4594-8a29-484d28a03257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/textarea</value>
      <webElementGuid>b2b2ee7a-90a6-41ab-9bb3-f224bdb66a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'judulBaruEn' and @name = 'judul_baru_en']</value>
      <webElementGuid>2f634770-4bb3-4acf-93c3-392c78c3feeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
