<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>judulBaru</name>
   <tag></tag>
   <elementGuidId>e38095ec-d84a-49ee-835d-bb3f9cc105b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#judulBaru</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='judulBaru']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7207c43c-38df-4b38-8b3c-7a6e8a6c1c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-field</value>
      <webElementGuid>bb1205ad-167a-4559-b55f-e27e9ae648c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>judulBaru</value>
      <webElementGuid>54776698-eeab-4533-9fc9-4c026aa75e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>judul_baru</value>
      <webElementGuid>62146a2d-4ff3-4353-8030-bed5fcb86f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>3048a4b6-bd4a-45ef-8b6e-eb0a4d6e153e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;judulBaru&quot;)</value>
      <webElementGuid>d8be613c-2128-423b-ad78-46bb67f985f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='judulBaru']</value>
      <webElementGuid>46ba3b61-2d91-458f-9b63-3bf5c62a1964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/textarea</value>
      <webElementGuid>519f3c7a-5351-4dcd-8258-402ce6785695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'judulBaru' and @name = 'judul_baru']</value>
      <webElementGuid>4640e5ff-b3c2-4c0d-b188-7b819a048a59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
