<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>penawaranTopikButton</name>
   <tag></tag>
   <elementGuidId>6b205508-794f-4f58-9e27-df8307734bbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='aside-menu']//a/*[text()='Penawaran Topik']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f1e0e30f-446f-4f7d-a9ae-9b097afd9119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://dev-thesis.its.ac.id/topik</value>
      <webElementGuid>54f82b60-697a-436a-8ccb-c9d426a2fb03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link-its d-flex justify-content-start align-items-center </value>
      <webElementGuid>6e3b9ba5-b01a-45b0-8e32-7851e76a704f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Penawaran Topik</value>
      <webElementGuid>c7ecb358-bd4b-4cf2-a891-b5c5e06d459a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aside-menu&quot;)/ul[@class=&quot;sidebar-nav ht-100p pd-y-10 scrollbar-its&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link-its d-flex justify-content-start align-items-center&quot;]</value>
      <webElementGuid>77e54fa9-dfa4-43f1-810b-c078b5aacedb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='aside-menu']/ul/li[2]/a</value>
      <webElementGuid>dbacc005-26dc-4627-b5fe-0b0e1c64efe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[2]/following::a[1]</value>
      <webElementGuid>a9d58621-ddba-42aa-ab9d-1ed4f8e5bf63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengumuman'])[1]/following::a[2]</value>
      <webElementGuid>95f9671d-37ff-4f32-a4b8-34bd07993f1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bimbingan Aktif'])[2]/preceding::a[1]</value>
      <webElementGuid>8bf26ce6-9ea8-40cc-9c1b-51bfe39af601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://dev-thesis.its.ac.id/topik')])[2]</value>
      <webElementGuid>bfeffcfd-4207-4618-aae1-54888fd7ea25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/ul/li[2]/a</value>
      <webElementGuid>2ed63a93-fdb1-4a20-8926-a9e4afd1faef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://dev-thesis.its.ac.id/topik' and (text() = 'Penawaran Topik' or . = 'Penawaran Topik')]</value>
      <webElementGuid>12201f28-4a53-418f-a8d5-0a7a4c24d1dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
