<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sidangButton</name>
   <tag></tag>
   <elementGuidId>612a3e7e-2b5b-4c32-87bf-96e67341a5eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='aside-menu']//*[text()='Sidang']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c569927b-01e7-465b-89ae-0477d37aea73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://dev-thesis.its.ac.id/sidang</value>
      <webElementGuid>d2126a14-9b7f-4e24-9a19-08aae237c5cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link-its d-flex justify-content-start align-items-center </value>
      <webElementGuid>3043e583-d4a7-4998-b4f8-6cb77b4f3fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sidang</value>
      <webElementGuid>aa44ccfb-27ed-4366-b982-e7b941328008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aside-menu&quot;)/ul[@class=&quot;sidebar-nav ht-100p pd-y-10 scrollbar-its&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link-its d-flex justify-content-start align-items-center&quot;]</value>
      <webElementGuid>61062727-0dc6-4133-9b88-1078b0622126</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='aside-menu']/ul/li[4]/a</value>
      <webElementGuid>9c6aef6c-c86c-42cc-b8e8-9d9c3356799f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bimbingan Aktif'])[2]/following::a[1]</value>
      <webElementGuid>2fc14401-19a2-4e51-b5dc-81673dc2bb7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penawaran Topik'])[2]/following::a[2]</value>
      <webElementGuid>891ce7bc-3b0b-4cbe-96c2-457759bdbb05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Repositori Dokumen'])[2]/preceding::a[1]</value>
      <webElementGuid>e1f21307-6f5e-48ed-9b5e-626caeccd1d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://dev-thesis.its.ac.id/sidang')])[3]</value>
      <webElementGuid>fb5b50e1-495f-40f3-9057-b214bf45f425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/ul/li[4]/a</value>
      <webElementGuid>63d2c04b-67c4-432f-82a8-9975e6299225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://dev-thesis.its.ac.id/sidang' and (text() = 'Sidang' or . = 'Sidang')]</value>
      <webElementGuid>82820800-117f-42c6-ba9e-9de0056a8645</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
