<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>judulEn</name>
   <tag></tag>
   <elementGuidId>141b8e26-e190-4121-b3fa-ae521094b031</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='judul_en']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#judul_en</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>76b9aec4-afc2-4b37-a0e7-c7525e1b5aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b91bff80-5b01-4f14-96e0-0de7f6124b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>JudulEn</value>
      <webElementGuid>d2a800af-96c2-4bdf-ad1c-711e5650cc62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>judul_en</value>
      <webElementGuid>eabf3b3c-6487-4ff8-8789-781f80966a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>judul_en</value>
      <webElementGuid>78fe8ec2-3418-4938-9685-04f952a129fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>260</value>
      <webElementGuid>17b945c3-ade0-40a7-8ff6-fadbf3f5ae05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;judul_en&quot;)</value>
      <webElementGuid>76461478-f63f-4fe3-b4cf-8b91fc136bd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='judul_en']</value>
      <webElementGuid>7b3a756b-6b56-473d-8d4a-bb48adebea9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/textarea</value>
      <webElementGuid>c2e64bb5-1213-4ab4-b801-1f58afe55605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'JudulEn' and @id = 'judul_en' and @name = 'judul_en']</value>
      <webElementGuid>8c5c2012-3d8c-4877-ac4e-f4627ac9c879</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
