<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>removeDosenButton</name>
   <tag></tag>
   <elementGuidId>d09cbe67-18d7-42ae-ba07-eaf64716c9e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='removeDosbing']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#removeDosbing</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7e8e57f7-4934-4bc8-9c4b-d641562417cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>removeDosbing</value>
      <webElementGuid>a8ffa291-c023-4737-97e8-39e9629bd059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7c1a677a-bf64-46d9-b37e-0b4f9f332420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-icon btn-its-custom-1 rounded-its-50p d-flex align-items-center</value>
      <webElementGuid>f803b8d0-f04b-4a16-b5f3-fade6ce8ffd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;removeDosbing&quot;)</value>
      <webElementGuid>15992473-d29d-4eee-b6b2-3ae7856d5094</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='removeDosbing']</value>
      <webElementGuid>f4d1f3a4-b004-46de-862d-a97d1359e660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inputFormRow']/button</value>
      <webElementGuid>1ac6f04a-1d97-4585-89b8-e9425f41cde4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dosen Pembimbing'])[2]/following::button[1]</value>
      <webElementGuid>57b3b8fa-34b1-4510-9091-fa008fab9e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mohon pilih pembimbing'])[1]/following::button[1]</value>
      <webElementGuid>b1941473-5437-439f-984e-5a74940ba2d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/preceding::button[2]</value>
      <webElementGuid>3efbfc30-86f7-4f6e-b91d-f8e7e43e27fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/button</value>
      <webElementGuid>e0de1f6d-7ec0-46e0-b1bf-3caeeed62e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'removeDosbing' and @type = 'button']</value>
      <webElementGuid>54150561-117a-423b-b3c0-ce0d44cd359e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
