<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>simpanButton</name>
   <tag></tag>
   <elementGuidId>768d5814-e91b-4f05-91b5-32fb6bb4c490</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-its-3.tx-poppins.tx-medium.float-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3c3201bd-5cfa-4dd0-b042-f23879fd0f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>176469ee-2dab-4ccc-8a37-eade145fd05e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-its-3 tx-poppins tx-medium float-right</value>
      <webElementGuid>f5e1eead-d790-4e88-8372-5affeb7376c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Simpan
                    </value>
      <webElementGuid>012af39a-ef73-4651-b24f-bd3ce45f3182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[1]/div[@class=&quot;content ht-100v pd-0&quot;]/div[@class=&quot;content-body mn-ht-100v d-flex flex-column&quot;]/div[@class=&quot;container pd-x-0 mg-t-50&quot;]/div[@class=&quot;row row-xs&quot;]/div[@class=&quot;col-12 col-sm-12 col-md-10 col-lg-7 col-xl-7 mg-b-10&quot;]/div[@class=&quot;card bd-0&quot;]/div[@class=&quot;card-body&quot;]/form[@class=&quot;needs-validation was-validated&quot;]/button[@class=&quot;btn btn-its-3 tx-poppins tx-medium float-right&quot;]</value>
      <webElementGuid>8b61f5ff-ad48-4969-bfa1-3e3b95622be9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>72abe748-e13a-4938-b7fd-7c778d0c85fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dosen Pembimbing'])[2]/following::button[3]</value>
      <webElementGuid>c71efab8-18b7-4d0b-b3cf-fa1bda098794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2021-2023 Institut Teknologi Sepuluh Nopember'])[1]/preceding::button[1]</value>
      <webElementGuid>3ee75e55-c6b6-4ceb-8c03-ac9f24f0449a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2021-2023 Institut Teknologi Sepuluh Nopember'])[2]/preceding::button[1]</value>
      <webElementGuid>4ed5cd44-f8df-433b-8ed8-7b954605101e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Simpan']/parent::*</value>
      <webElementGuid>0b68e626-99ff-41ee-8479-f25b19aac898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>6e4ba3ca-c687-48e2-8572-160a672da04f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                        Simpan
                    ' or . = '
                        Simpan
                    ')]</value>
      <webElementGuid>6afde651-5fe8-4073-ab86-1f212c66fdae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
